//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMM.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SS
    {
        public int t { get; set; }
        public long u { get; set; }
        public long d { get; set; }
        public int transfer_enable { get; set; }
        public int port { get; set; }
        public string password { get; set; }
        public sbyte @switch { get; set; }
        public sbyte enable { get; set; }
        public sbyte isrest { get; set; }
        public System.DateTime last_rest_time { get; set; }
        public System.DateTime expiration_time { get; set; }
        public System.DateTime create_time { get; set; }
        public int userid { get; set; }
    }
}
