//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SSMM.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SSMMEntities : DbContext
    {
        public SSMMEntities()
            : base("name=SSMMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<Notice> Notice { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<Recharge> Recharge { get; set; }
        public virtual DbSet<ServerNode> ServerNode { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<SS> SS { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<CouponCode> CouponCode { get; set; }
    }
}
